<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Content\**" />
    <Compile Remove="wwwroot\Content\**" />
    <Content Remove="Content\**" />
    <Content Remove="wwwroot\Content\**" />
    <EmbeddedResource Remove="Content\**" />
    <EmbeddedResource Remove="wwwroot\Content\**" />
    <None Remove="Content\**" />
    <None Remove="wwwroot\Content\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchoolManagement.Application\SchoolManagement.Application.csproj" />
    <ProjectReference Include="..\SchoolManagement.Identity\SchoolManagement.Identity.csproj" />
    <ProjectReference Include="..\SchoolManagement.Infrastructure\SchoolManagement.Infrastructure.csproj" />
    <ProjectReference Include="..\SchoolManagement.Persistence\SchoolManagement.Persistence.csproj" />
  </ItemGroup>

</Project>
